- .circleci/config.yml
- Gemfile
- Gemfile.lock
- README.md
- lib/tasks/plantain.rake
- spec/fixtures/ead/rarebooks/WC127.EAD.xml
Advances #22 by implementing Rake tasks for indexing PULFA EAD files.  Also adds `pry-byebug` as a development dependency.
> Adds PULFA indexing Rake tasks

- Capfile
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/application_controller.rb
- config/blacklight.yml
- config/database.yml
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/secrets.yml
Closes #13.
- Removes blacklight_locale_picker gem. It currently has a syntax error.
- Removes Ruby version from Gemfile. Staging server is currently running 2.4.5
- Tether gem is no longer used, removed reference to it in javascript.
- Updated Solr URLs in blacklight.yml to match plantain rake tasks
> 13 capistrano

- Gemfile
- Gemfile.lock
> Remove chromedriver-helper and selenium in favor of webdrivers

- Gemfile
- Gemfile.lock
> Add Honeybadger.

- .rubocop.yml
- config/downloads.yml
- lib/plantain/traject/ead2_config.rb
- lib/tasks/plantain.rake
Also provides a default configuration for EAD downloads (without this, one cannot view finding aids indexed into Plantain)
> Introduces updates to the Traject EAD configuration for fixing EAD indexing

- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/staging.rb
- config/environments/production.rb
- config/routes.rb
- config/sidekiq.yml
> Add sidekiq

- app/jobs/index_job.rb
- solr/conf/solrconfig.xml
Commits were timing out both in dev and on staging.
refs #12
> Don't commit to solr in code; rely on solrconfig

- README.md
> Document indexing in development

- Rakefile
- lib/tasks/plantain.rake
> Rake tasks need environment to load properly

- .rubocop.yml
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/ead/mudd/publicpolicy/MC221.EAD.xml
initially just has one spec, for dao indexing.
@jrgriffiniii I'm not sure if you want this to build on moving forward. I thought I was going to need to index daos but it turned out they are already in there (I just wasn't seeing them in my solr I guess because they're stored but not indexed). Feel free to just close it if you don't want it!
> Add test for the traject configuration

- .gitignore
> added eads/pulfa to gitignore

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/header.scss
- app/controllers/application_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- app/views/shared/_header_account_dropdown.html.erb
- app/views/shared/_header_navbar.html.erb
- config/initializers/devise.rb
- config/locales/blacklight.en.yml
- config/routes.rb
- db/migrate/20181115163306_devise_create_users.rb
- db/migrate/20191112203518_add_cas_to_users.rb
- db/schema.rb
- spec/models/user_spec.rb
adapted from figgy's [CAS integration](https://github.com/pulibrary/figgy/commit/83d1a2433be882f71047ad7ab13b942d39b92ea9#diff-a4275c3adf0e6810f2de8c6b215f6645)
closes #82 and #55
> integrates CAS with plantain

- app/assets/javascripts/application.js
> require jquery3 in applicationjs

- spec/features/traject/ead2_indexing_spec.rb
> finished all the required tests in ticket 84

- .circleci/config.yml
to fix circle deploy issues according to figgy and orangelight
> edited circle.ci config file 

- .circleci/config.yml
> Test Ruby 2.6 in CI

- .circleci/config.yml
- .solr_wrapper.yml
- lib/tasks/plantain.rake
- solr/conf/schema.xml
- solr/conf/solrconfig.xml
> Update solr and postgres containers for circleci

- lib/plantain/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> indexed component ids without their parent id

- .circleci/config.yml
- .coveralls.yml
- .gitignore
- .rubocop.yml
- README.md
- app/jobs/index_job.rb
- app/renderers/universal_viewer.rb
- config/application.rb
- config/blacklight.yml
- config/database.yml
- config/deploy.rb
- config/initializers/pulfalight_config.rb
- config/secrets.yml
- lib/pulfalight/normalized_date.rb
- lib/pulfalight/normalized_title.rb
- lib/pulfalight/traject/ead2_config.rb
- lib/pulfalight/year_range.rb
- lib/tasks/pulfalight.rake
- package.json
- spec/features/traject/ead2_indexing_spec.rb
Ready for review. If approved, I'll merge and deploy once the box is re-provisioned with https://github.com/pulibrary/princeton_ansible/pull/1399
closes #95
> Remove all traces of plantain name; use pulfalight

- .lando.yml
- README.md
- config/application.rb
- config/blacklight.yml
- config/lando_env.rb
> Use Lando for Solr Dev/Test

- app/models/arclight/parent.rb
- app/overrides/arclight/parent.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/ead/mss/C1588.EAD.xml
- spec/models/arclight/parent_spec.rb
> Fix breadcrumbs

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
- spec/requests/catalog_controller_spec.rb
- spec/requests/catalog_request_spec.rb
Resolves #241, and I believe that this should advance progressing towards developing the JSON objects which can be consumed by Vue components.
> Implements JSON serialization for EAD collections

- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/ead/C0614.EAD.xml
> Ensures that Traject indexes nested component trees for collections with deeply-nested components

- .gitignore
- README.md
- app/jobs/index_job.rb
- config/repositories.yml
- lib/tasks/pulfalight.rake
- spec/jobs/index_job_spec.rb
> Adds an initial repository configuration file

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/helpers/pulfalight_helper.rb
- app/models/solr_document.rb
- app/presenters/collection_html_presenter.rb
- app/presenters/collection_presenter.rb
- app/presenters/component_html_presenter.rb
- app/presenters/component_presenter.rb
- app/presenters/document_presenter.rb
- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/helpers/pulfalight_helper_spec.rb
- spec/requests/catalog_request_spec.rb
> Indexes and renders collection-level notes on collection pages and for component pages

- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/ead/mss/location_aspace.EAD.xml
> Updating the Traject config. to extract barcodes from <container> elements and indexing them into the barcodes_ssim field

- lib/tasks/pulfalight.rake
> Update pulfalight:seed task to run indexing inline and commit immediately

- app/controllers/catalog_controller.rb
- spec/requests/catalog_controller_spec.rb
> Render the full Solr document when accessing the raw route

- bin/solr
We were only indexing into test previously.
> Index solr documents into lando development solr

- app/services/table_of_contents_builder.rb
- spec/services/table_of_contents_builder_spec.rb
> Allow TOC to build when a component has a single child component

- lib/tasks/pulfalight.rake
Makes development a little easier.
> Allow users to index a document immediately without Sidekiq

- app/views/catalog/_show_collection_title.html.erb
- spec/features/catalog_view_spec.rb
> Remove separate date from the collection title

- Gemfile
- Gemfile.lock
Lets me use language server features in VIM.
> Add Solargraph

- app/assets/stylesheets/application.scss
It doesn't work via webpack for whatever reason. Fixes style of search results.
> Require Arclight via Sprockets.

- .circleci/config.yml
- .tool-versions
- yarn.lock
> Updates the Node.js dependencies for release 12.18.3

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/show_collection.scss
- app/helpers/pulfalight_helper.rb
- app/views/catalog/_show_collection_title.html.erb
- spec/features/catalog_view_spec.rb
> Make collection title a link to the top-level collection record

- app/helpers/application_helper.rb
> Don't show home page header on show pages

- app/controllers/catalog_controller.rb
- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/catalog_view_spec.rb
> Break apart subjects into smaller categories and sort alphabetically

- .circleci/config.yml
- package.json
- source/setup-jest.js
- yarn.lock
Setups jest framework for future testing. Runs test during CI.
Closes #401
> Add jest testing framework

- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> Ensure staff names are not included in names facet

- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
Neither are implemented yet, this just gets rid of filler.
Closes #409, Closes #410
These features will be implemented in #104 and #105.
> Remove Ask a Question and Suggest a Correction

- app/renderers/universal_viewer.rb
- app/views/catalog/_component_summary.html.erb
- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/views/catalog/_arclight_viewer_default.html.erb_spec.rb
This also fixes indexing of direct digital objects.
Direct digital objects are all the digital objects only associated with that component. Also indexed are all digital objects deep, but it doesn't look like those are used for anything in particular now?
Closes #223
>  Render viewer based on direct digital objects.

- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- lib/pulfalight/traject/ead2_indexing.rb
- spec/features/traject/ead2_indexing_spec.rb
> Fixes breadcrumbs in index view.

- app/models/search_builder.rb
- app/overrides/arclight/helper_overrides.rb
- app/views/catalog/_search_form.html.erb
- spec/features/catalog_search_spec.rb
> Group search results by collection by default

- app/controllers/catalog_controller.rb
- spec/requests/catalog_request_spec.rb
> Ensure that searching by collection code returns the correct result

- app/controllers/catalog_controller.rb
- spec/requests/catalog_request_spec.rb
> Enable searching by component id

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/jobs/aspace_index_job.rb
- app/services/aspace/client.rb
- config/config.yml
- lib/pulfalight/traject/ead2_config.rb
- spec/fixtures/aspace/mss/C1588.xml
- spec/fixtures/aspace/repositories.json
- spec/jobs/aspace_index_job_spec.rb
- spec/services/aspace/client_spec.rb
- spec/support/archivespace_stub.rb
This is just a first pass and the the very beginning, but it should get some EADs in for us.
> Index from ArchivesSpace

- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/aspace/mss/C1588.xml
This is necessary for Aeon requesting.
> Index container_location_codes_ssm in component

- app/assets/javascripts/application.js
- app/assets/javascripts/focus.js
> Adds Focus to Homepage Searchbox

- app/assets/stylesheets/modules/toc.scss
- app/javascript/pulfalight/toc.es6
> Automatically scroll TOC on view.

- app/values/aeon_request.rb
- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
- spec/models/solr_document_spec.rb
> Hide non-leaf node containers from requesting.

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/models/event.rb
- app/services/aspace/client.rb
- app/services/aspace/indexer.rb
- db/migrate/20201029231133_create_events.rb
- db/schema.rb
- spec/models/event_spec.rb
- spec/services/aspace/client_spec.rb
- spec/services/aspace/indexer_spec.rb
- spec/support/archivespace_stub.rb
> ArchivesSpace Updates-Only Indexing

- app/controllers/catalog_controller.rb
> Remove "Level" facet

- app/views/catalog/_requests.html.erb
> Make Create a Research Account button go to the right place.

- app/javascript/components/RequestCart.vue
> Add tip note to request cart.

- .rubocop.yml
- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> Extref links in EAD should resolve to <a> links.

- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- spec/features/catalog_view_spec.rb
> Ensure userestrict HTML links are rendered.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/research_help.scss
- app/controllers/research_help_controller.rb
- app/views/catalog/_requests.html.erb
- app/views/research_help/research_help.html.erb
- config/routes.rb
- spec/controllers/research_help_controller_spec.rb
- spec/features/accessibility_spec.rb
Populate it with initial content
And link to it from home
closes #368
> Create research help page

- app/javascript/components/AddToCartButton.vue
- app/javascript/components/CartViewToggle.vue
- package.json
- spec/javascript/pulfalight/addToCartButton.spec.js
- spec/javascript/pulfalight/cartViewToggle.spec.js
- spec/javascript/setup.js
- yarn.lock
Gets a testing infrastructure in and starts to show how to test our vue components.
Relevant documentation:
https://testing-library.com/docs/vue-testing-library/examples
https://testing-library.com/docs/dom-testing-library/api-queries
> First few Request Cart tests.

- app/views/catalog/_collection_summary_abstract.html.erb
- app/views/catalog/_correction_modal.html.erb
- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
- spec/features/accessibility_spec.rb
> Add WCAG tests for collection show page, component show page, and suggest form

- app/assets/stylesheets/_overrides.scss
- app/assets/stylesheets/arclight.scss
- spec/features/accessibility_spec.rb
Increase font size and lighten background for "view more" toggle, to
improve contrast
refs #323
> Check accessibility on search results

- lib/tasks/pulfalight.rake
> Add new test EADs

- lib/pulfalight/normalized_date.rb
- spec/features/catalog_view_spec.rb
- spec/services/table_of_contents_builder_spec.rb
> Update normalized date indexing so that normalized titles contain correctly formatted dates

- app/controllers/catalog_controller.rb
- spec/features/facets_spec.rb
> Reconfigure access facet, push to the top, and make always open

- app/controllers/catalog_controller.rb
- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/catalog_view_spec.rb
> Index topics, subject, and genre terms as ssim so they work as facets

- app/jobs/aspace_index_job.rb
- spec/fixtures/aspace/mss/C1588-internal.xml
- spec/jobs/aspace_index_job_spec.rb
> Don't index unpublished EADs

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_question_modal.scss
- app/controllers/contact_controller.rb
- app/forms/ask_a_question_form.rb
- app/javascript/pulfalight/pulfalight_loader.es6
- app/mailers/contact_mailer.rb
- app/views/catalog/_ask_a_question_form.html.erb
- app/views/catalog/_correction_modal.html.erb
- app/views/catalog/_question_modal.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/contact_mailer/contact.html.erb
- app/views/layouts/blacklight/base.html.erb
- config/routes.rb
- spec/controllers/contact_controller_spec.rb
- spec/features/accessibility_spec.rb
- spec/features/catalog_view_spec.rb
- spec/forms/ask_a_question_form_spec.rb
- spec/views/catalog/_ask_a_question_form.html.erb_spec.rb
> Ask a Question

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- solr/conf/schema.xml
- solr/conf/solrconfig.xml
- spec/requests/catalog_request_spec.rb
Closes #116
Related to pulibrary/pul_solr#241
> Search by EADID & Box/Folder Number

- app/javascript/components/CartViewToggle.vue
> Ensure count badge lines up next to cart

- app/javascript/components/RequestCart.vue
- spec/features/catalog_view_spec.rb
- Most importantly, ensures that there is a closed button when the cart is empty.
- Adds feature tests for request cart
Closes #504
> Improve empty request cart behavior

- app/assets/stylesheets/layouts/home.scss
> Prevent tiling of hero background on home page

- app/views/shared/_header_navbar.html.erb
> Update landing page title #563

- app/assets/stylesheets/modules/toc.scss
> Adds visual focus indicator in TOC

- app/controllers/catalog_controller.rb
> Add labels for topics/subject terms/genreform facets

- app/controllers/catalog_controller.rb
- spec/requests/catalog_request_spec.rb
> Allow lowercase collection ID searches.

- app/views/catalog/_component_summary.html.erb
> Don't query for Figgy resources & also display download link.

- app/controllers/catalog_controller.rb
- spec/features/facets_spec.rb
> Remove "In the Library" from top facet.

- app/views/shared/_header_navbar.html.erb
> Fix banner text.

- app/models/search_builder.rb
- spec/features/catalog_view_spec.rb
- spec/requests/catalog_request_spec.rb
Work towards #560
This also includes a missing test from #589
> Boost collections in search results

- app/views/catalog/_question_modal.html.erb
> Fix FAQ links.

- app/views/layouts/blacklight/base.html.erb
- app/views/shared/_analytics.html.erb
> Add Google Analytics.

- app/views/research_help/research_help.html.erb
> Link AV materials directly offsite.

- app/models/search_builder.rb
> Boost collection results twice as hard as title.

- lib/pulfalight/traject/ead2_component_config.rb
- spec/controllers/toc_controller_spec.rb
- spec/features/accessibility_spec.rb
- spec/features/catalog_view_spec.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/models/solr_document_spec.rb
- spec/models/solr_document_tree_spec.rb
- spec/requests/catalog_request_spec.rb
- spec/services/table_of_contents_builder_spec.rb
> Don't index aspace_

- app/models/solr_document.rb
- lib/pulfalight/traject/ead2_component_config.rb
- spec/requests/catalog_controller_spec.rb
> Adjust JSON endpoint to work for Figgy.

- app/controllers/catalog_controller.rb
- app/views/catalog/_collection_child.html.erb
- spec/requests/catalog_controller_spec.rb
Closes #575
This also fixes tests in master caused by some conflicting merges.
> Use "Description" as the label for scope note everywhere.

- config/deploy/production.rb
> Add pulfalight-prod2

- app/views/catalog/_show_collection.html.erb
- spec/features/catalog_view_spec.rb
> Adds Ask A Question button to top level of collection

- app/views/catalog/_requests.html.erb
> Fix Create a Research Account button.

- app/models/search_builder.rb
- spec/requests/catalog_request_spec.rb
> Strip quotes from searches.

- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_collection_expanded.html.erb
- app/views/catalog/_show_default.html.erb
- config/locales/en.yml
> Rename tab headers.

- app/javascript/components/RequestCart.vue
- package.json
- spec/features/catalog_view_spec.rb
- yarn.lock
> Sets focus on request cart, when opened

- app/controllers/catalog_controller.rb
- app/helpers/pulfalight_helper.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/catalog_view_spec.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/requests/catalog_request_spec.rb
Closes #336
This also uncomments a few tests I noticed no longer needed commented.
> Render ARK on the collection summary.

- .rubocop.yml
- config/initializers/repository_contact_info_patch.rb
- config/repositories.yml
- spec/arclight/repository_spec.rb
> Add link to Ask us a Question for repository contact.

- app/assets/stylesheets/jstree-theme.scss
- app/assets/stylesheets/modules/_document_access_badge.scss
- app/services/table_of_contents_builder.rb
- app/views/catalog/_show_collection_title.html.erb
- spec/features/accessibility_spec.rb
- spec/features/catalog_view_spec.rb
> Add digital content icon to ToC/Header

- .circleci/config.yml
- app/assets/stylesheets/_overrides.scss
- app/views/shared/_header_account_dropdown.html.erb
- app/views/shared/_header_navbar.html.erb
- package.json
- yarn.lock
> Adds 'Request Help' to LibraryHeader and fixes mobile view

- app/models/solr_document.rb
- spec/features/catalog_view_spec.rb
> Don't always display digital content tag.

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/services/aspace/indexer.rb
- config/deploy.rb
- config/deploy/production.rb
- config/schedule.rb
- lib/tasks/reindexing.rake
- spec/services/aspace/indexer_spec.rb
>  Run incremental indexing every night at 7 PM.

- app/values/aeon_request.rb
- spec/models/solr_document_spec.rb
> Ensure boxes aren't added to folders in requests.

- app/assets/javascripts/application.js
- app/assets/javascripts/tabs.js
- app/assets/stylesheets/_overrides.scss
- app/assets/stylesheets/modules/toc.scss
- app/views/catalog/_collection_summary.html.erb
- app/views/catalog/_component_summary.html.erb
- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_show_tab_panes.html.erb
- app/views/catalog/_show_tabs.html.erb
- spec/features/catalog_view_spec.rb
- vendor/assets/javascripts/jstree.js
fixes #570 
Some accessibility issues were also fixed in this branch:
1. fixes #495
2. fixes to Heading Sequence issues (unticketed) 
3. aria roles wrt the tabs feature (unticketed)
> Fixes collection overview tab bug 

- solr/conf/solrconfig.xml
Companion to https://github.com/pulibrary/pul_solr/pull/262
> Synchronize pulfalight configuration.

- app/views/catalog/_requests.html.erb
> Adds Princeton non-affiliated language to Research Account instructions.

- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- lib/pulfalight/traject/ead2_indexing.rb
- spec/features/traject/ead2_indexing_spec.rb
> Don't index DAOs for relative paths.

- app/forms/ask_a_question_form.rb
- app/forms/suggest_a_correction_form.rb
- spec/controllers/contact_controller_spec.rb
- spec/forms/ask_a_question_form_spec.rb
- spec/forms/suggest_a_correction_form_spec.rb
> Email routing fixes for libanswers

- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/catalog_search_spec.rb
- spec/features/traject/ead2_indexing_spec.rb
> Components return on match of collection title.

- config/routes.rb
- spec/requests/catalog_request_spec.rb
> Redirect legacy pulfa URIs to new pulfalight path

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_correction_modal.scss
- app/views/catalog/_correction_modal.html.erb
- spec/views/catalog/_correction_modal.html.erb_spec.rb
Include a link to Archival Language document
Connected to #681
> Add instructions to correction modal

- app/assets/stylesheets/modules/show_collection.scss
> Simple fix to alignment of collection title on wrap

- config/deploy/production.rb
> Add pulfalight-worker1

- config/schedule.rb
> Perform incremental updates hourly.

- app/assets/stylesheets/modules/header.scss
- app/javascript/components/RequestCart.vue
- app/views/shared/_header_navbar.html.erb
> Banner text update

- spec/jobs/aspace_index_job_spec.rb
- spec/spec_helper.rb
> Bug fix: order dependent test failure

- solr/conf/solrconfig.xml
Updates pulfa config to have new weightings for title.
Companion to https://github.com/pulibrary/pul_solr/pull/265
Work towards #560
> Copy pulfa config from pul_solr.

- app/views/catalog/_requests.html.erb
> Update Aeon Registration Link

- app/views/catalog/_facet_pagination.html.erb
Closes #545
Pulled from https://github.com/pulibrary/orangelight/pull/2142
Apparently I fixed this and never sent a PR.
> Remove extra <span> tag.

- app/views/catalog/_requests.html.erb
> Update main page text.

- lib/tasks/pulfalight.rake
advances pulibrary/pul_solr#238
> Update pul_solr reference to use new default branch

- app/views/shared/_header_navbar.html.erb
> Update header text

- app/javascript/components/RequestCart.vue
- spec/javascript/pulfalight/requestCart.spec.js
* Adds a note field to the request cart.
* Adjusts CSS for request cart to allow for scroll no matter how many
components there are.
- This uses CSS3, but works in all major browsers.
Closes #671
> Add Note to request cart.

- app/jobs/aspace_index_job.rb
- spec/jobs/aspace_index_job_spec.rb
> Delete unpublished records from Solr on sync.

- lib/pulfalight/traject/ead2_indexing.rb
- spec/features/catalog_view_spec.rb
- spec/requests/catalog_request_spec.rb
> Don't index prefercite field, generate it.

- app/values/aeon_request.rb
- spec/models/solr_document_spec.rb
> Use item-level title in call slip.

- app/controllers/partner_exports_controller.rb
- app/views/partner_exports/pacscl.html.erb
- config/routes.rb
- spec/controllers/partner_exports_controller_spec.rb
- spec/requests/partner_exports_request_spec.rb
> Add PACSCL page.

- app/controllers/partner_exports_controller.rb
- app/views/layouts/empty.html.erb
- app/views/partner_exports/pacscl.html.erb
- spec/controllers/partner_exports_controller_spec.rb
- spec/requests/partner_exports_request_spec.rb
> Adds a root node and breaks between links for PACSCL.

- app/controllers/partner_exports_controller.rb
- app/views/partner_exports/pacscl.html.erb
- config/routes.rb
- spec/requests/partner_exports_request_spec.rb
> Special renderer for PACSCL

- app/values/aeon_request.rb
- spec/models/solr_document_spec.rb
> Truncate access string for Aeon.

- app/mailers/contact_mailer.rb
- spec/controllers/contact_controller_spec.rb
- spec/forms/ask_a_question_form_spec.rb
- spec/forms/suggest_a_correction_form_spec.rb
> Set from address in contacts to be provided email.

- app/models/pulfalight/document/xml_export.rb
- spec/requests/catalog_controller_spec.rb
> Fix XML display for PACSCL

- app/assets/stylesheets/modules/search.scss
- app/views/catalog/_arclight_index_default.html.erb
- app/views/catalog/_group_header_default.html.erb
- app/views/catalog/_index_default.html.erb
- spec/features/catalog_search_spec.rb
> Add call number to search results collection header.

- app/controllers/catalog_controller.rb
- app/views/shared/_header_account_dropdown.html.erb
> Remove Bookmarks

- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/aspace/generated/mss/C0879.processed.EAD.xml
> Ensuring that the language_ssm and language_sim fields have values indexed which are fully cleaned of punctuation characters

- app/views/catalog/_arclight_index_compact_default.html.erb
- app/views/catalog/_arclight_index_default.html.erb
- app/views/catalog/_group_header_default.html.erb
- spec/features/catalog_search_spec.rb
Closes #890 
We'll have to fix deprecation warnings again, but this adds a test so this doesn't happen again.
> Fix title display

- app/views/catalog/_arclight_index_group_document_default.html.erb
- spec/features/catalog_search_spec.rb
> Add scopecontent to grouped component display.

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/values/pulfalight/location_code.rb
- app/values/pulfalight/unrecognized_location_error.rb
- lib/pulfalight/normalized_box_locations.rb
- lib/pulfalight/traject/ead2_component_config.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/catalog_view_spec.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/lib/pulfalight/normalized_box_locations_spec.rb
> Calculate physical location summary from box locations

- app/services/aspace/client.rb
- spec/services/aspace/client_spec.rb
> Raise a shorter message on connection error

- app/values/aeon_request.rb
- spec/models/solr_document_spec.rb
It contains the box locator.
Fixes #931. Confirmed by @faithc
> ItemInfo4 should choose FirstValue

- app/services/aspace/client.rb
- lib/pulfalight/normalized_title.rb
- spec/lib/pulfalight/normalized_title_spec.rb
closes #898
This allowed the resource that was failing in that honeybadger error to index into my dev instance:
> Fix NormalizedTitle to handle nil title

- config/environments/production.rb
log filled up on a worker box despite rotation in place
> increase production log level

- app/controllers/catalog_controller.rb
> Render links in abstract.

- app/services/aspace_fixture_generator.rb
- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/fixtures/aspace/generated/mss/C0662.EAD.xml
> Add support for HTML in abstract links.

- app/controllers/catalog_controller.rb
> Display URLs in collection descriptions.

- app/views/catalog/_question_modal.html.erb
> Update link targets for FAQ items in Ask a Question modal

- app/javascript/pulfalight/query_figgy.es6
- spec/javascript/pulfalight/query_figgy.spec.js
Related to https://github.com/pulibrary/figgy/pull/4827 — making the same wording change in Pulfalight.
> Updating notice for restricted content

- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> Fix repository indexing for deeply nested components 

- Gemfile
- Gemfile.lock
> Force sidekiq 5.x

- config/deploy/production.rb
> Add surge boxes.

- docs/aeon_integration.md
> Add a little bit more about aeon tests

- app/controllers/catalog_controller.rb
> Add processinfo to component page.

- .circleci/config.yml
> Use new circleci image

- app/controllers/catalog_controller.rb
> Add phystech to components.

- app/views/catalog/_correction_form.html.erb
- spec/controllers/contact_controller_spec.rb
> Update suggest a correction message.

- app/values/aeon_request.rb
- spec/values/aeon_request_spec.rb
> Don't use a combined Site for Aeon requests

- docs/relevance.md
> Add documentation on search relevance use cases / functionality

- app/controllers/catalog_controller.rb
> Don't require that audience_ssi is set.

- app/values/aeon_request.rb
- spec/values/aeon_request_spec.rb
> Add oversize folders as top containers for requesting.

- app/assets/stylesheets/layouts/home.scss
- app/views/catalog/_feedback_welcome.html.erb
- app/views/catalog/_home.html.erb
- app/views/catalog/_requests.html.erb
closes #962
for consideration.
> Add feedback welcome text to home page

- app/models/pulfalight/document/xml_export.rb
- spec/requests/catalog_controller_spec.rb
Solves issues with XML rendering of certain components.
Closes #799
> Remove namespaces from component XML

- README.md
> Document aspace api connection troubleshooting

- app/assets/stylesheets/layouts/home.scss
- app/controllers/contact_controller.rb
- app/controllers/feedback_controller.rb
- app/forms/report_harmful_language_form.rb
- app/javascript/pulfalight/pulfalight_loader.es6
- app/mailers/contact_mailer.rb
- app/views/catalog/_ask_a_question_form.html.erb
- app/views/catalog/_home.html.erb
- app/views/catalog/_report_harmful_language_form.html.erb
- app/views/contact_mailer/report.html.erb
- app/views/feedback/ask_a_question.html.erb
- app/views/feedback/report.html.erb
- app/views/feedback/suggest.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_header_ask_us_dropdown.html.erb
- app/views/shared/_header_menu_dropdown.html.erb
- app/views/shared/_header_navbar.html.erb
- config/routes.rb
- spec/controllers/contact_controller_spec.rb
- spec/controllers/feedback_controller_spec.rb
- spec/forms/report_harmful_language_form_spec.rb
Todo: click behavior and submission form
refs #779
> Adds Ask Us! menu to website main nav

- app/jobs/aspace_index_job.rb
- app/jobs/index_job.rb
- app/jobs/sync_to_figgy_job.rb
- app/services/aspace/indexer.rb
- spec/jobs/aspace_index_job_spec.rb
- spec/jobs/sync_to_figgy_job_spec.rb
- spec/services/aspace/indexer_spec.rb
- spec/support/stubbing.rb
- spec/support/with_queue_adapter.rb
> Tell figgy to sync after indexing updated EADs

- app/jobs/sync_to_figgy_job.rb
- spec/jobs/sync_to_figgy_job_spec.rb
> Send the correct parameter to Figgy.

- app/assets/stylesheets/layouts/catalog_show.scss
- app/assets/stylesheets/modules/buttons.scss
- app/javascript/pulfalight/pulfalight_loader.es6
- app/views/catalog/_feedback_welcome.html.erb
- app/views/catalog/_harmful_language_modal.html.erb
- app/views/catalog/_show_tab_panes.html.erb
- app/views/layouts/blacklight/base.html.erb
- spec/features/catalog_view_spec.rb
> Add harmful language button to components

- app/jobs/sync_to_figgy_job.rb
- config/config.yml
- spec/jobs/sync_to_figgy_job_spec.rb
- spec/support/stubbing.rb
> Use access token when posting to Figgy refresh_remote_metadata route

- app/views/catalog/_hours.html.erb
- spec/controllers/hours_controller_spec.rb
- spec/features/accessibility_spec.rb
- spec/fixtures/files/libcal/18717.json
> Fix Firestone hours.

- .circleci/config.yml
- .tool-versions
- Gemfile
- Gemfile.lock
- app/javascript/components/PulfaDataTable.vue
- babel.config.js
- bin/webpack
- bin/webpack-dev-server
- package.json
- yarn.lock
Closes #1029 
- Updates node
- Updates webpacker gem
- Updates js packages
- Updates circle config node installation and base image
Tested on staging.
> Update Node to 16.15

- app/models/pulfalight/document/xml_export.rb
- spec/requests/partner_exports_request_spec.rb
> Prepend repository name with "Princeton University Library: "

- app/views/catalog/_hours.html.erb
> #1079 - Change library names on landing page

- app/views/catalog/_correction_modal.html.erb
- app/views/catalog/_feedback_welcome.html.erb
- app/views/catalog/_harmful_language_modal.html.erb
- app/views/catalog/_show_tab_panes.html.erb
- app/views/feedback/report.html.erb
- db/schema.rb
- spec/views/catalog/_correction_modal.html.erb_spec.rb
> Updates the Report Harmful Language form description (sudden priority ticket)

- app/views/shared/_header_navbar.html.erb
> Delete the Welcome/COVID information banner

- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/robots.yml
- config/routes.rb
- package.json
- solr/conf/solrconfig.xml
- spec/services/robots_generator_service_spec.rb
- yarn.lock
Works towards #108 
- Install blacklight_dynamic_sitemap gem
- Build robots.txt after deploy
> Add sitemap

- README.md
> Add URL of production site to README

- app/views/catalog/_requests.html.erb
> Add link to special collections

- lib/pulfalight/traject/ead2_component_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> Index components' ID as an MD5 for sitemaps.

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/shared/_header_menu_dropdown.html.erb
- config/application.rb
- config/authorization.yml
- config/routes.rb
- spec/factories/user.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- Point 'Your Accout' link to Aeon
- Restrict sidekiq route to authorized netids
Closes #1076
> Replace CAS login with Aeon login

- app/values/aeon_request.rb
- spec/values/aeon_request_spec.rb
> Change order of item number and box number

- app/assets/stylesheets/arclight.scss
- app/assets/stylesheets/modules/_document_access_badge.scss
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/presenters/online_content_badge.rb
- app/views/catalog/_arclight_index_default.html.erb
- app/views/catalog/_arclight_index_group_document_default.html.erb
- app/views/catalog/_group_header_default.html.erb
- app/views/catalog/_show_collection_title.html.erb
- solr/conf/solrconfig.xml
- spec/features/catalog_search_spec.rb
- spec/features/catalog_view_spec.rb
- spec/presenters/online_content_badge_spec.rb
Closes #1053 
Companion pul_solr PR: https://github.com/pulibrary/pul_solr/pull/352
> Add online content badge to search results

- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
- spec/requests/catalog_controller_spec.rb
> Display text date instead of normalized value for collections

- app/assets/stylesheets/_overrides.scss
- app/views/layouts/blacklight/base.html.erb
- app/views/shared/_footer.html.erb
> Stick footer to bottom of page

- app/controllers/catalog_controller.rb
- spec/features/catalog_view_spec.rb
> Display "Other Finding Aids" under "Find Related Materials"

- app/helpers/pulfalight_helper.rb
- app/models/solr_document.rb
- app/views/catalog/_show_collection_header_default.html.erb
- spec/helpers/pulfalight_helper_spec.rb
> Make thumbnail image a clickable link to repository

- app/jobs/aspace_index_job.rb
> Require from rails root

- lib/pulfalight/traject/ead2_component_config.rb
- spec/services/aspace/indexer_spec.rb
Closes #1188
https://github.com/pulibrary/pulfalight/blob/pulfalight_combined_headings/app/models/solr_document.rb#L358
> Index components combined fields to *_tsm.

- app/helpers/pulfalight_helper.rb
- spec/helpers/pulfalight_helper_spec.rb
> Address exception raised by DAO with incorrectly formatted link

- README.md
along with pulibrary/pul-it-handbook#136 this closes #1183
> Update README to indicate we send full IP list to lyrasis

- app/assets/javascripts/typeahead_override.js
> Configure typeahead with hint=false

- app/views/about/archival_language.html.erb
> Textual changes to Statement on Archival Descriptions

- .circleci/config.yml
> Remove license file that makes build error

- .circleci/config.yml
> Run CI nightly so we can address failures promptly

- app/controllers/catalog_controller.rb
> Don't display system identifier in component view.

- app/assets/stylesheets/modules/toc.scss
- app/javascript/pulfalight/toc.es6
- app/services/table_of_contents_builder.rb
- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
- spec/features/catalog_view_spec.rb
- spec/services/table_of_contents_builder_spec.rb
> Add table of contents online toggle.

- Gemfile
- Gemfile.lock
- app/jobs/sync_to_figgy_job.rb
- config/authorization.yml
- config/blacklight.yml
- config/config.yml
- config/database.yml
- config/deploy/qa.rb
- config/environments/qa.rb
- config/redis.yml
- config/robots.yml
- config/secrets.yml
- spec/jobs/sync_to_figgy_job_spec.rb
> Add QA environment

- app/views/catalog/_component_summary.html.erb
- spec/features/catalog_view_spec.rb
> Add online content badge to component view

- app/javascript/pulfalight/toc.es6
- Build TOC only when element exists in document
- Scroll only when a element is selected
Confirmed that this is working in staging.
> Fix JS loading issues with TOC

- app/assets/stylesheets/layouts/catalog_show.scss
- app/assets/stylesheets/modules/_document_access_badge.scss
- app/views/catalog/_show_collection_title.html.erb
> Fix online banner styles.

- app/assets/stylesheets/modules/_document_access_badge.scss
- app/javascript/pulfalight/toc.es6
- app/presenters/online_content_badge.rb
- spec/services/table_of_contents_builder_spec.rb
> Enhance online content tooltip

- app/controllers/catalog_controller.rb
> Add userestrict and custodhist to component display.

- app/javascript/components/PulfaDataTable.vue
- app/javascript/components/RequestCart.vue
- app/models/solr_document.rb
- app/services/child_table_builder.rb
- app/values/aeon_request.rb
- app/values/pulfalight/location_code.rb
- config/location_codes.yml
- spec/javascript/pulfalight/requestCart.spec.js
- spec/values/aeon_request_spec.rb
- spec/values/pulfalight/location_code_spec.rb
> Request Cart Location Info

- app/javascript/pulfalight/toc.es6
- app/views/catalog/_show_default.html.erb
> Make table of contents online toggle persistent.

- .circleci/config.yml
- .lando.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
> Updated circle ci config and lando config to postgres 15

- app/values/aeon_request.rb
- spec/values/aeon_request_spec.rb
> Fix aeon request rendering when there's no accessrestrict.

- config/initializers/redis_config.rb
- config/initializers/sidekiq.rb
> Update sidekiq configuration to not use redis client

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/dropdown-help-text.scss
- app/components/dropdown_help_text_component.rb
- app/controllers/catalog_controller.rb
- app/controllers/concerns/multiple_algorithms.rb
- app/helpers/pulfalight_helper.rb
- app/models/online_content_search_builder.rb
- app/views/catalog/_algorithm_select.html.erb
- config/config.yml
- config/initializers/pulfalight_config.rb
- config/locales/blacklight.en.yml
- solr/conf/solrconfig.xml
- spec/features/search_algorithms_spec.rb
- spec/requests/multiple_algorithms_spec.rb
> Add functionality to switch search algorithms

- config/aeon.yml
- config/config.yml
Atlas recommended we change this per this issue https://github.com/pulibrary/pulfalight/issues/1348.
> Update aeon URL per atlas recommendation.

- config/deploy/qa.rb
advances #1355
companion PR: https://github.com/pulibrary/princeton_ansible/pull/4542
> Deploy to the new qa machines

- README.md
Regine and Anna went through the instructions and found that neither of
our current global protect IPs were in the resulting list.
> Update the ip access instructions

- config/deploy/production.rb
- config/deploy/staging.rb
> Deploy to new prod and staging boxes

- Gemfile
- Gemfile.lock
- app/checks/aspace_status.rb
- app/checks/solr_status.rb
- config/initializers/health_monitor.rb
- config/routes.rb
- spec/checks/solr_status_spec.rb
- spec/requests/health_check_spec.rb
> Add Health Endpoint

- app/views/about/archival_language.html.erb
> Per LSC directive, remove the Additional Resources section.

- config/schedule.rb
- lib/tasks/reindexing.rake
* Update the incremental index to only run through the day
* make both indexing jobs write to default rails log
* delete a comment that didn't make sense with the job it was next to and that I just generally didn't understand
closes #1383
> Add a full nightly index

- app/checks/smtp_status.rb
- config/initializers/health_monitor.rb
- spec/requests/health_check_spec.rb
References pulibrary/lae-blacklight#381
> Add Pony Express Monitor

- Gemfile
- Gemfile.lock
Our prod redis is too old for Sidekiq Pro right now.
> Revert to older Sidekiq version.

- config/initializers/health_monitor.rb
> remove honeybadger health notification

- app/javascript/components/RequestCart.vue
- package.json
- yarn.lock
> Fix note propagation to Aeon

- .circleci/config.yml
> [circleic] Update browser tools and chrome driver

- Gemfile.lock
> upgrade change_the_subject gem to latest version

- config/environments/production.rb
The current mail relay's rejecting all mail with FROM addresses from folks responding to the form.
Refs https://github.com/pulibrary/princeton_ansible/issues/5204
> Revert the mail relay in Pulfalight.

- app/views/catalog/show.html.erb
> Remove start over button.

- config/initializers/health_monitor.rb
- spec/requests/health_check_spec.rb
Borrowed from https://github.com/pulibrary/figgy/pull/6534 by @tpendragon
Closes #1449
> Root health.json errors rarely, filtered checks error if they fail.

- .circleci/config.yml
> Try constraining rubocop parallelization to stop crashing CI

- .circleci/config.yml
- app/checks/smtp_status.rb
- spec/requests/health_check_spec.rb
> SMTP check should happen every 5 minutes

- spec/rails_helper.rb
> Fix deprecation warning about fixture_paths

- app/views/catalog/_component_summary.html.erb
- spec/features/catalog_view_spec.rb
> restriction badge not a link at the series level

- app/javascript/components/AddToCartButton.vue
- app/javascript/components/RequestCart.vue
- app/javascript/test/addToCartButton.spec.js
- app/models/solr_document.rb
- app/views/catalog/_show_tab_panes.html.erb
- spec/features/catalog_view_spec.rb
- spec/requests/health_check_spec.rb
> notifies user of restricted items in request cart

- config/deploy.rb
> writes sha of current deploy to /version.txt

- app/views/catalog/_correction_modal.html.erb
- app/views/feedback/suggest.html.erb
- spec/views/catalog/_correction_modal.html.erb_spec.rb
Work towards #1479 
In draft until `wording-update` branch is green.
> Update wording on suggest a correction modal

- Gemfile.lock
> Update change_the_subject to 0.3.6

- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- spec/features/catalog_view_spec.rb
> Added dimensions_ssm field to component view

- app/values/aeon_request.rb
- spec/values/aeon_request_spec.rb
> Updated site info conf for Aeon

- Gemfile.lock
> Updated rack to 2.2.11

- Gemfile.lock
> Update security net-imap

- Gemfile.lock
> Update nokogiri for security

- lib/pulfalight/traject/ead2_config.rb
- spec/features/traject/ead2_indexing_spec.rb
> Index multiple languages as an array

- Gemfile.lock
> Update rack to 2.2.13 for security

- app/assets/stylesheets/arclight.scss
- app/presenters/online_content_badge.rb
- app/views/catalog/_algorithm_select.html.erb
- app/views/catalog/_show_collection.html.erb
- app/views/catalog/_show_default.html.erb
- spec/features/catalog_search_spec.rb
- spec/features/catalog_view_spec.rb
- spec/features/search_algorithms_spec.rb
- spec/presenters/online_content_badge_spec.rb
- spec/presenters/online_content_banner_spec.rb
- spec/services/table_of_contents_builder_spec.rb
> Updated has online content to has online material

- config/environments/test.rb
> Changed config.cache_classes to equal false

- Gemfile
- Gemfile.lock
- spec/features/catalog_view_spec.rb
- spec/rails_helper.rb
Closes #1510 
A few small changes to get this test suite passing for me locally.
> Small changes to make test suite pass locally

- app/javascript/pulfalight/pulfalight_loader.es6
Finishes fixing #1516. Thanks @seanaery
> Remove date range color configuration.

- Gemfile.lock
> Updated change_the_subject to 0.4.2

- app/views/about/av_materials.html.erb
> Update the AV statement.

- app/views/shared/_header_navbar.html.erb
> Add a banner notifying patrons of June closure.

- package.json
- yarn.lock
to get more recent versions of dependencies
> Update the http-proxy-to-socks dependency

- app/components/pulfalight/search_bar_component.html.erb
- app/components/pulfalight/search_bar_component.rb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_header_navbar_noscript.html.erb
silence Deprecation Warning about render_search_bar
> Move search bar to a view component

- app/services/table_of_contents_builder.rb
- spec/features/catalog_view_spec.rb
- spec/features/toc_spec.rb
Closes #769 
**This PR was created, in part, with the assistance of an LLM. Please review carefully.**
> Initial implementation

- lib/tasks/pulfalight.rake
> Use proxy for indexing task

- .rubocop.yml
- app/controllers/toc_controller.rb
- app/javascript/pulfalight/toc.es6
- app/services/table_of_contents_builder.rb
- spec/features/toc_spec.rb
- spec/services/table_of_contents_builder_spec.rb
Closes #1522 
https://github.com/user-attachments/assets/8d745fd0-dadd-412b-becd-0549312cdde9
> Open TOC to first component with online content

- app/controllers/application_controller.rb
- app/models/pulfalight/document/xml_export.rb
- spec/features/catalog_search_spec.rb
- spec/requests/partner_exports_request_spec.rb
> Don't error when xml is requested for a component that doesn't exist

- app/javascript/pulfalight/toc.es6
- app/services/table_of_contents_builder.rb
- spec/features/toc_spec.rb
> Preserves online ToC toggle state by collection

- .github/ISSUE_TEMPLATE/issue_template.md
This is based on the draft at
https://github.com/pulibrary/.github/pull/14/files.
I just couldn't take the three hundred buttons anymore after clicking create issue.
> Use one issue template.

- app/javascript/pulfalight/pulfalight_loader.es6
- app/javascript/store/index.es6
- spec/features/catalog_view_spec.rb
- spec/features/request_cart_spec.rb
Use the local storage event and vue `replaceState` to sync cart between tabs
closes #1554
> Sync cart items between tabs

- app/javascript/pulfalight/toc.es6
Closes #1582 
Had some trouble replicating this in dev because our fixtures don't have enough components. Ended up downloading the full C1491 EAD and overwriting the fixture temporarily.
> Adjust TOC scroll offset to accommodate online toggle

- app/presenters/summary_storage_note_presenter.rb
- spec/presenters/summary_storage_note_presenter_spec.rb
> Remove unneeded code in summary storage presenter

- app/assets/stylesheets/layouts/catalog_show.scss
- app/assets/stylesheets/modules/_accessrestrict_notice.scss
- app/views/catalog/_restriction_warning.html.erb
- app/views/catalog/_show_upper_metadata_default.html.erb
- spec/features/catalog_view_spec.rb
- spec/views/catalog/_component_summary.html.erb_spec.rb
> Visually prioritize access note when content is restricted

- app/views/catalog/_correction_modal.html.erb
- app/views/feedback/suggest.html.erb
> Add link for problematic language.

- app/views/layouts/blacklight/base.html.erb
- app/views/shared/_analytics.html.erb
- app/views/shared/_analytics_noscript.html.erb
Work towards pulibrary/dpul-collections#709
> Add analytics tags with google tag manager.
