pulibrary/pulfalight

config/deploy.rb

Please see https://github.com/capistrano/capistrano/issues/1930 for reference.

Locks the Capistrano version to a minor release (rather than a patch release)

---

README.md
lib/plantain/normalized_date.rb
lib/plantain/normalized_title.rb
lib/plantain/traject/ead2_config.rb
lib/plantain/year_range.rb
lib/tasks/plantain.rake
lib/tasks/pulfa.rake

Resolves #40 by addressing the following:
- Providing steps within the README for retrieving the PULFA EAD Documents
- Implementing the `NormalizedDate`, `NormalizedTitle`, and `YearRange` Classes for overriding the default EAD parsing
This also includes an overridden the EAD 2002 configuration for the Traject parser in order to inject the overridden classes.

Providing steps within the README for retrieving the PULFA EAD Documents

---

spec/spec_helper.rb

Not sure why bundler isn't doing this for us, but it's annoying to have
to do it every time you want to add a breakpoint.t

Require pry for tests

---

.solr_wrapper.yml

Solr was unable to start in development mode without this.

specify solr version 8.2.0 for solr_wrapper

---

.circleci/config.yml

Otherwise CircleCI uses NodeJS for 8.x LTS releases.

Upgrading NodeJS to lts/dubnium

---

.rubocop.yml
app/overrides/arclight/digital_object_override.rb
app/renderers/universal_viewer.rb
app/views/viewers/_simple_link.html.erb
config/application.rb
lib/plantain/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb
spec/views/catalog/_arclight_viewer_default.html.erb_spec.rb

refs #162 
looks like this now for non-manifest objects:

Display digital objects as links if they aren't manifests

---

app/jobs/index_job.rb
lib/pulfalight/traject/ead2_config.rb
lib/tasks/pulfalight.rake

This should address cases where PULFA finding aid EADs are not being indexed properly with the necessary Rake tasks.

Fixes issues with seeding the Solr Collection with PULFA EADs and ensures that IndexJob commits to Solr

---

lib/pulfalight/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb
spec/fixtures/ead/C0002.xml

Later we'll have to put the containers into the source documents, but
for now don't recognize them as top-level components.

Do not index DSC[2].

---

lib/pulfalight/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb

Without an accumulator there's no reason to not convert them to text. In fact, leaving them as not text results in empty fields.
Closes #203

Don't leave search fields as Nokogiri Nodes

---

lib/pulfalight/traject/ead2_config.rb

Resolves #245 and deprecates #248

Ensuring that the overidden DigitalObject is used by Traject for indexing

---

README.md
app/models/solr_document.rb
app/services/citation_resolver_service.rb
config/citations.yml
config/repositories.yml
lib/pulfalight/traject/ead2_component_config.rb
lib/pulfalight/traject/ead2_config.rb
lib/pulfalight/traject/ead2_indexing.rb
spec/features/traject/ead2_indexing_spec.rb
spec/requests/catalog_request_spec.rb

Implementing support for indexing the generated citations for EAD collections and components using the `prefercite` field; Ensuring that this is rendered on the show views for both Collections and Components. Resolves #150. 
Please see the following example:

Generates "preferred citation" fields for Collections and Components

---

.gitignore
lib/tasks/pulfa.rake

This is necessary in order to advance #278

Implements a Rake Task for checking out PULFA EADs exported from ArchivesSpace

---

app/controllers/catalog_controller.rb
spec/requests/catalog_request_spec.rb

Ensuring that, when users search for a collection ID, that they are redirected to the collection show page (should the collection exist). Advances #79

Ensuring that users are redirected to the show page when searching for a valid collection ID

---

lib/pulfalight/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb

- Unless this is helpful for developers of the future.
- Also fixes a regression in a spec that was introduced in a previous commit. Branch needed to be rebased before merging.

Fix spec regressions and remove unneeded comment

---

app/assets/stylesheets/modules/toc.scss
app/assets/stylesheets/variables/colors.scss
app/views/catalog/_show_collection.html.erb
app/views/catalog/_show_default.html.erb

Updates table of contents style to more closely match wireframe designs.

Update table of contents style

---

app/assets/stylesheets/layouts/catalog_show.scss
app/views/catalog/_collection_access.html.erb
app/views/catalog/_collection_description.html.erb
app/views/catalog/_collection_find_more.html.erb
app/views/catalog/_collection_history.html.erb
app/views/catalog/_collection_summary.html.erb
app/views/catalog/_collection_summary_overview.html.erb

- Remove redundant tab titles
- Reformats collection overview page slightly to better match tab name
Closes #394

Remove redundant tab titles

---

README.md

Removing reference to db:setup and db:migrate, and a bit of
reorganization that hopefully adds clarity

Update development setup notes

---

app/assets/stylesheets/modules/header.scss
app/views/shared/_header_navbar.html.erb

@tpendragon One thing that I didn't add to the LUX component is a cookie that knows if you've dismissed the banner, so we don't show it on subsequent pages. If that's desirable, I'll add it. Otherwise, I will remove the "dismissible" attribute and the banner will be ever-present.

Adds LUX announcements Banner

---

spec/features/accessibility_spec.rb

TOC is generally good with regards to WCAG standards. There are a couple errors that are integrated into the js.tree library. Hopefully future versions will correct these.
Closes #322

Adds accessibility test for table of contents

---

app/javascript/components/RequestCart.vue
package.json
spec/javascript/pulfalight/cartViewToggle.spec.js
spec/javascript/pulfalight/requestCart.spec.js

Clear request cart when form is submitted to Aeon
This is achieved by copying data from form into shadow form when form is submitted, then clearing form and submitting shadow form.
Other details:
- adjust indentation in RequestCart template for consistency
- move `<form>` tags to contain smallest possible number of lines
- Duplicate `<form>` into a shadow form
- Fix use of state in RequestCart to allow test to properly mock
fixes #446

446 clear cart

---

app/views/shared/_header_navbar.html.erb

This balances the page a bit better.
before:
after:

Increase max width of header to match search results

---

app/assets/stylesheets/layouts/home.scss

brings it closer to the wireframes and tidies up text wrapping in headers
before:
after:

Widen home content a bit

---

app/services/aspace/client.rb
spec/fixtures/aspace/repositories.json
spec/services/aspace/client_spec.rb

We changed our migration method, so we no longer need this.

Remove recent_repositories in ASpace Client

---

app/assets/stylesheets/layouts/home.scss

And remove the dark outline
This softens the design a bit in that area. The button itself already seems a significant attention-draw and the previous weight of this design element seemed a bit incongruous.
before:
after:

Lighten box around "create a research account" button

---

app/assets/stylesheets/modules/search.scss

Also had to do this in orangelight:
https://github.com/pulibrary/orangelight/pull/1914/files
Before:
after:

Ensure search box and submit button are same height as dropdown

---

app/controllers/catalog_controller.rb
lib/pulfalight/traject/ead2_component_config.rb
spec/features/facets_spec.rb
spec/features/traject/ead2_indexing_spec.rb

Items whose children have online content shouldn't appear when you facet
to only those things with online content.

Display + facet only items which themselves have online content

---

lib/pulfalight/traject/ead2_component_config.rb
solr/conf/solrconfig.xml

Lowering it resulted in too many results being returned. However, collection UnitID and box/folder info had to be concatenated to work.

Increase "mm" value.

---

app/models/solr_document.rb
spec/requests/catalog_controller_spec.rb

Was causing a parsing error in Figgy. Date_created should be the
human-readable view of the date, created is an actual date string if it
exists.

Fix mixed up date_created and created

---

app/services/table_of_contents_builder.rb
spec/services/table_of_contents_builder_spec.rb

Closes #576
ToC looks like this when navigating directly to a component now, expanding its direct children:

Table of contents opens direct children when clicked on.

---

app/javascript/pulfalight/query_figgy.es6
spec/javascript/pulfalight/query_figgy.spec.js

Closes #666
It was broken because we don't have `aspace_` in our component IDs anymore.

Fix Pulfalight Figgy Viewer

---

spec/controllers/research_help_controller_spec.rb

Fixes deprecation warning:
```
DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers. (called from block (3 levels) in <top (required)> at /Users/bess/projects/pulfalight/spec/controllers/research_help_controller_spec.rb:9)
```

Fix deprecation warning

---

.rubocop.yml
app/values/aeon_request.rb
spec/models/solr_document_spec.rb

Adding a grouping identifier for Aeon which includes the EADID ensures
that only the same box merges into the same call slip.
Closes #696
Special thanks to https://blog.rockarch.org/technical-overview-of-ead-requesting-with-aeon and @helrond (which is funny, because PULFA2 is referenced there. :joy:)

Group by a unique identifier for requests.

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/services/storage_notes.rb
spec/features/catalog_view_spec.rb

Display collection level storage note on component pages

---

README.md
spec/support/capybara_selenium.rb

To turn off headless mode, run specs with RUN_IN_BROWSER=true set
Fixes #699

Run feature specs in browser by setting an environment variable

---

app/jobs/aspace_index_job.rb
app/jobs/index_job.rb
app/models/pulfalight/document/xml_export.rb
app/models/solr_document.rb
app/models/xml_cache.rb
app/services/aspace/client.rb
db/migrate/20210405214959_create_xml_caches.rb
db/migrate/20210405220028_add_ead_id_to_xml_cache.rb
db/schema.rb
lib/pulfalight/traject/ead2_config.rb
spec/jobs/aspace_index_job_spec.rb
spec/requests/catalog_controller_spec.rb
spec/support/archivespace_stub.rb

Closes #107
This adds an XML caching layer in ActiveRecord. It's the simplest low level cache store we have around and by utilizing one row per ead_id we don't have to worry about it getting too big or having a bunch of stale content.

XML Display for Collections

---

app/assets/stylesheets/layouts/catalog_show.scss

This just makes the UV scroll to the right if there's not enough space
to be full screen. It doesn't look great, but researchers can access the
material.

Add a temporary stopgap measure for UV display.

---

.circleci/config.yml
yarn.lock

Ensures that the changes from https://github.com/pulibrary/pulfalight/pull/820 are ported with an updated CircleCI configuration (otherwise the caching for the CI environment breaks the tests).

Bump hosted-git-info from 2.8.8 to 2.8.9

---

Gemfile
Gemfile.lock

For awhile we had to maintain a locally forked copy of the
archivesspace-client gem, but the fix we made locally has since been
incorporated upstream.
Note this is the same fix we made for abid: https://github.com/pulibrary/abid/issues/15
Fixes #839

Use a released version of archivesspace-client

---

README.md
lib/tasks/pulfalight.rake

Use rake servers:start and rake servers:stop, like we do in other
projects, to reduce team cognitive overhead.

Standardize starting and stopping

---

app/views/catalog/_arclight_index_compact_default.html.erb
app/views/catalog/_arclight_index_default.html.erb
app/views/catalog/_group_header_default.html.erb

DEPRECATION WARNING: passing a Symbol to link_to_document is deprecated and
will be removed in Blacklight 8

Address a few deprecation warnings

---

app/jobs/aspace_index_job.rb
config/repositories.yml
lib/pulfalight/missing_repository_error.rb
lib/pulfalight/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb
spec/jobs/aspace_index_job_spec.rb

Improved error handling when there's not an Arclight::Repository for the collection getting indexed
closes #979

Provide basic configuration for East Asian Collection

---

config/repositories.yml

In particular, the lack of a thumbnail was causing the error. closes #991

Add more configuration for the east asian collection

---

.lando.yml

Shaves off ~ 18 seconds from the test suite, and these services don't need the app mount anyways.

Don't mount the app root in Lando

---

app/controllers/catalog_controller.rb
app/jobs/aspace_index_job.rb
app/models/search_builder.rb
app/views/catalog/record_not_found.json.jbuilder
config/config.yml
lib/pulfalight/traject/ead2_component_config.rb
lib/pulfalight/traject/ead2_config.rb
spec/features/catalog_search_spec.rb
spec/fixtures/aspace/mss/C1588-internal.xml
spec/jobs/aspace_index_job_spec.rb

This allows Figgy to hit the JSON endpoints for non-discoverable resources, but doesn't show them in search results or the HTML/Raw routes.
Closes #1010
Closes pulibrary/figgy#5050
Ansible PR: https://github.com/pulibrary/princeton_ansible/pull/2990

Index unpublished EADs, don't make them discoverable.

---

app/values/aeon_request.rb
spec/values/aeon_request_spec.rb

This also adds a test to make sure future fields we add get combined, or
at least the test will fail until we decide whether to group them or
not.
Closes #1046

Add Site to the GroupingFields.

---

.circleci/config.yml
.lando.yml
db/schema.rb

Update ci and lando to use postgres 13

---

lib/pulfalight/traject/ead2_component_config.rb
lib/pulfalight/traject/ead2_config.rb
spec/features/traject/ead2_indexing_spec.rb

Works towards #935 
Fixes issue where acqinfo values are not searchable and do not appear in hit highlighting.

Index acqinfo_teim

---

app/assets/stylesheets/_overrides.scss
app/views/shared/_footer.html.erb

Closes #1123 
Modeled #main-container styling after the one in DPUL to make footer sticky.

Stick footer to the bottom of the page

---

app/assets/stylesheets/layouts/catalog_show.scss
app/assets/stylesheets/layouts/home.scss
app/assets/stylesheets/modules/buttons.scss
app/javascript/components/ChildTable.vue
app/views/catalog/_requests.html.erb
app/views/catalog/_show_collection_expanded.html.erb
app/views/catalog/_show_tab_panes.html.erb

Advances #111 
Before
After
Before
After
Before
After
Before
After

Improve mobile responsiveness

---

app/assets/stylesheets/arclight.scss

Increase contrast of collection box in search results

---

app/assets/stylesheets/layouts/collection_show.scss
app/assets/stylesheets/modules/toc.scss
app/javascript/pulfalight/media_queries.es6
app/javascript/pulfalight/pulfalight_loader.es6
app/views/catalog/_show_collection.html.erb
app/views/catalog/_show_collection_expanded.html.erb
app/views/catalog/_show_default.html.erb

Closes #111 by creating a collapsible Table of Contents so scrolling on mobile devices isn't trapped within it. Now, the Table of Contents will be collapsed by default on mobile devices.
Before
After (Expanded)
After (Collapsed)

Allow collapsing of Table of Contents

---

app/controllers/catalog_controller.rb
spec/features/catalog_view_spec.rb

We were indexing all the right things, we just needed to use the scopecontent_ssm field instead of the collection_description_ssm, since that's the field that has the `_combined` field.
Closes #817

Render headers for collection description.

---

spec/features/traject/ead2_indexing_spec.rb

There's no need to compute values, just use the values we know are in
the fixture.
This refactor resulted in a redundant test so I deleted one of them.
fixes #1256

Test against data values known to be in fixture

---

config/blacklight.yml

Closes #1262 
This allows indexing to work by waiting for Solr to update for a longer time. We think Solr might still have problems, but this gets pulfalight indexing.

Increase solr timeout.

---

app/assets/stylesheets/layouts/catalog_show.scss
app/assets/stylesheets/modules/_document_access_badge.scss
app/assets/stylesheets/modules/_document_extent_badge.scss
app/presenters/online_content_badge.rb
app/views/catalog/_arclight_index_default.html.erb
app/views/catalog/_group_header_default.html.erb
app/views/catalog/_index_document_attributes.html.erb

- Remove duplicate styles
- Bring all badges into a row below the title
Makes the change for both index views: grouped and ungrouped
Uses badge styles that were initially developed for the component page,
so now they're blue in both places. Reduced gap between badges a bit on
both index and component page.
closes https://github.com/pulibrary/pulfalight/issues/1172
screenshots:

Search results badge row

---

app/helpers/pulfalight_helper.rb
spec/helpers/pulfalight_helper_spec.rb

Closes #1051 
Blocked by urls to assign to library buildings.

Add library building to search results breadcrumbs

---

app/models/solr_document.rb
app/values/aeon_request.rb
spec/values/aeon_request_spec.rb

This fixes the problem where ReCAP would be displayed, which is not a site researchers can go to.
Closes #1154

Base location hint off of Site.

---

config/initializers/redis_config.rb
config/initializers/sidekiq.rb
config/redis.yml

closes #1117
This updates the redis timeout and also updates the way we configure redis, doing it through the sidekiq initializer.
According to documentation, `Redis.current` should work still with the version of the redis gem used in pulfalight, but when I tried to access it it only returned default configurations.
Tested this new configuration on staging and jobs successfully process. And doing it this way should set us up for gem upgrades.
Used https://github.com/pulibrary/figgy/commit/14d7104803fc2bae176747b119f7928ae016ebe3 as a reference for this.

Set timeout for redis client

---

config/repositories.yml

The Engineering Library has moved to Fine Hall; I've updated the name and address with what Willow gave me.

Update eng repo

---

app/forms/ask_a_question_form.rb
app/forms/report_harmful_language_form.rb
app/forms/suggest_a_correction_form.rb
app/mailers/contact_mailer.rb

This will let us only send emails from worker nodes, which will stop errors from showing to users and let us retry emails that come in.
Work in response to #1361

Background email

---

Gemfile
Gemfile.lock
app/models/pulfalight/document/xml_export.rb
spec/requests/catalog_controller_spec.rb

- Add debug gem to get around load errors with pry debugging
- Use refs when fetching document id, it stores the original id
closes #1116

Use refs instead of ID when fetching xml

---

Gemfile

This keeps nginx from trying to load a version of stringio that's not in the bundle.

Don't include debug in prod

---

app/assets/javascripts/tabs.js
spec/features/catalog_view_spec.rb

Closes #1380
As an aside, this tab situation's quite a lot. We render all the tabs on every page, but don't switch to them with javascript. It's very odd, artifact of implementing wireframes out of Arclight probably?

Don't hide component summary for c_ids without underscores.

---

.circleci/config.yml
app/javascript/entrypoints/application.js
app/javascript/test/addToCartButton.spec.js
app/javascript/test/cartViewToggle.spec.js
app/javascript/test/components/FiggyViewer.spec.js
app/javascript/test/requestCart.spec.js
package.json
yarn.lock

Uses standard for javascript linting. We are already using standard rules in other [projects like Figgy](https://github.com/pulibrary/figgy/blob/main/.eslintrc.js#L3).
- Add globalFormParams props
- Add standardjs

Lint with standardjs

---

Gemfile.lock
config/initializers/health_monitor.rb
spec/requests/health_check_spec.rb

I set the latency lower than we did for Figgy, since all the jobs are system initiated nothing should be sitting around for a long time.

Add Sidekiq monitoring.

---

app/views/about/archival_language.html.erb
app/views/about/av_materials.html.erb
app/views/about/requesting_materials.html.erb
app/views/about/research_account.html.erb
app/views/about/search_tips.html.erb
app/views/feedback/ask_a_question.html.erb
app/views/feedback/report.html.erb
app/views/feedback/suggest.html.erb

This also fixes lux headings, which we missed migrating tags for.
Closes #1392

Update Statement on Archival Language

---

.rubocop.yml
config/initializers/honeybadger_downtime_hook.rb
spec/honeybadger_spec.rb

Work towards pulibrary/figgy#6394
This enables us to do a search in Honeybadger to exclude all maintenance items: `-context.maintenance_window:"true"`

Add a context for errors in maintenance window.

---

app/views/shared/_header_navbar.html.erb

This replicates the look of the launch banner we used when the site was created.

Use lux banner and place it at the top of the page so it's visible

---

solr/conf/solrconfig.xml
spec/features/catalog_search_spec.rb

In certain views the query wasn't including the parent_ssim field, which is necessary to build the breadcrumbs. This fixes tests, will have to replicate it in the Solr repository.
Refs #1153
Solr PR: https://github.com/pulibrary/pul_solr/pull/425

Ensure breadcrumbs render in all views.

---

app/helpers/pulfalight_helper.rb

This should prevent some empty fields from rendering like in https://findingaids.princeton.edu/catalog/C1432_c020?onlineToggle=false
Closes #1438 
Tested and worked in staging.

Force ArclightHelper to render before PulfalightHelper

---

config/initializers/health_monitor.rb

We can't do anything about it when we're notified, and we're hammering them in a way they can't handle.

Remove ASpace monitor.

---

app/assets/stylesheets/modules/_document_access_badge.scss
app/views/catalog/_restricted_badge.html.erb
spec/features/catalog_view_spec.rb

Now the link color is the same @tpendragon I also updated the test.
Ref #1368

Added link to restrictions badge

---

app/javascript/components/RequestCart.vue
app/javascript/test/requestCart.spec.js
spec/features/catalog_view_spec.rb

Updated text for shopping cart delivery note

---

app/assets/stylesheets/layouts/home.scss
app/views/catalog/_feedback_welcome.html.erb
app/views/catalog/_home.html.erb
app/views/catalog/_responsible_collection_description.html.erb

Addresses #1478 
In draft until `wording-update` branch is green.

Update feedback welcome text

---

app/assets/stylesheets/modules/toc.scss
app/views/catalog/_show_collection.html.erb
app/views/catalog/_show_default.html.erb
spec/features/catalog_view_spec.rb

Refactored online content toggle for accessibility 

---

.rubocop.yml
config/initializers/deprecation.rb

They're overwhelming our log aggregation.
Closes #1512

Don't display deprecations in production logs.

---

app/helpers/pulfalight_helper.rb
app/views/catalog/_collection_access.html.erb
app/views/catalog/_collection_description.html.erb
app/views/catalog/_collection_find_more.html.erb
app/views/catalog/_collection_history.html.erb
app/views/catalog/_collection_summary_abstract.html.erb
app/views/catalog/_collection_summary_overview.html.erb
app/views/catalog/_show_upper_metadata_default.html.erb

This eliminates the following deprecation warning: 
```
DEPRECATION WARNING: #show_presenter is deprecated; use #document_presenter instead. (called from generic_should_render_field? at /home/circleci/pulfalight/app/helpers/pulfalight_helper.rb:43)
```

Change show_presenter to document_presenter to fix deprecation warning

---

app/controllers/catalog_controller.rb

Fixes this deprecation warning in the test runs: 
> DEPRECATION WARNING: DeprecatedObjectProxy without a deprecator is deprecated (called from show at /home/circleci/pulfalight/app/controllers/catalog_controller.rb:21)

Fix deprecation warning for DeprecatedObjectProxy

---

Gemfile
Gemfile.lock
README.md
app/services/aspace_proxy_manager.rb
lib/tasks/pulfalight.rake
package.json
spec/spec_helper.rb
yarn.lock

This means we don't have to bother Lyrasis with requests to change our
IP ranges anymore through VPN.
To test you'll have to pull this down, run `yarn install`, and then you should be able to connect to VPN, delete one of the fixtures in `spec/fixtures/aspace/generated/mss/*`, and run `bundle exec rake pulfalight:fixtures:refresh_aspace_fixtures`

Proxy ASpace API interactions in rake tasks through a worker box.

---

app/values/aeon_request.rb

Support for #1491
We didn't always know about the parent/child relationship of containers,
so we had complex filtering logic. Now we know that a top container is
any container that doesn't have a child, and those are the requestable
containers.
This is in draft pending confirmation from @ccleeton and @faithc that call slips should have all containers on a record that don't have a child, but this is passing all our edge case tests that got added in the past.

Simplify top container logic.

---

config/schedule.rb

along with https://github.com/pulibrary/princeton_ansible/pull/6113 this closes #1250
ansible-generated cron jobs have been deleted from the servers

updated the schedule for removing temp db entries

---

app/javascript/components/ChildTable.vue
app/javascript/components/PulfaDataTable.vue
app/services/child_table_builder.rb
spec/features/catalog_view_spec.rb

For consideration, this is the simplest implementation to satisfy #1523. It results in a small footprint for the badge and maximal context for its meaning.

Add an "online' column to contents list

---

app/controllers/catalog_controller.rb
app/presenters/online_content_badge.rb
app/views/catalog/_component_summary.html.erb
lib/pulfalight/traject/ead2_component_config.rb
spec/features/catalog_view_spec.rb
spec/presenters/online_content_badge_spec.rb

When a user clicks the online content badge, the system performs a search for the online content within that component.
Closes #1521

Make online content badge clickable

---

app/javascript/pulfalight/toc.es6

https://github.com/pulibrary/pulfalight/blob/main/app/javascript/pulfalight/toc.es6#L11
This code is not needed as a null value for `pulfalightOnlineToggle` is equivalent to false. And also, this code has a bug so doesn't do anything anyway.
https://github.com/pulibrary/pulfalight/blob/main/app/javascript/pulfalight/toc.es6#L51-L54

Remove unneeded toc code

---

app/presenters/summary_storage_note_presenter.rb

Code removed in #1591 was re-introduced in #1588 and references a method
that no longer exists.
This code was hit in staging, probably due to a stale index (the same record did not error in a after deploying main). A full
reindex is underway on staging.

Remove code that was accidentally re-introduced

---

config/application.rb
lib/pulfalight/middleware/no_file_uploads.rb
lib/pulfalight/middleware/no_file_uploads_spec.rb

part of OIT security theater and a yank and paste of
https://github.com/pulibrary/orangelight/pull/5128
the PR rejects any attempt to upload files
related to https://princeton.service-now.com/service?sys_id=d878ef12876f6e907f147487cebb35ad&view=sp&id=ticket&table=incident

reject requests that contain file uploads
